<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository {

    public function findLast($limit) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('b')
                        ->from('AppBundle:Book', 'b')
                        ->orderBy('b.createdAt', 'DESC')
                        ->setMaxResults($limit)
                        ->getQuery()
                        ->getResult()
        ;
    }

}
