<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findWithCount() {
        return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('c AS category, COUNT(b.id) AS count_books')
                ->from('AppBundle:category', 'c')
                ->leftJoin('c.books', 'b')
                ->groupBy('c.id')
                ->getQuery()
                ->getResult()
                ;
    }
    
}
